#!/usr/bin/env python3
"""make_ue_rule_tests — turns every pure rule test into an Unreal automation test ("Murdar.Rules.<System>").

Usage:  python Tools/make_ue_rule_tests.py <Handoff dir> <module source root> <output dir>
  e.g.  python Tools/make_ue_rule_tests.py Handoff Source/Murdar_GameDev Source/Murdar_GameDev/Tests/Rules

For each Handoff/<System>/Tests/*.cpp it writes RuleTest_<System>.cpp: the test's code inside its own namespace,
main() renamed, the rule header includes rewritten to their path in the module, wrapped in
IMPLEMENT_SIMPLE_AUTOMATION_TEST. Same checks, run by the engine (Session Frontend > Automation, or
UnrealEditor-Cmd ... -ExecCmds="Automation RunTests Murdar.Rules; Quit"). Re-run after changing a test.
Only systems whose rule header exists in the module are generated (the rest aren't integrated yet).
"""
import os
import re
import sys

STD = ['algorithm', 'array', 'cmath', 'cstdint', 'cstdio', 'deque', 'functional', 'map', 'set', 'string', 'vector']


def find_header(source_root, name):
    for base, _, files in os.walk(source_root):
        if name in files:
            return os.path.relpath(os.path.join(base, name), source_root).replace(os.sep, '/')
    return None


def convert(test_src, source_root, system):
    """Returns (body for inside the namespace, rule includes for global scope, missing headers)."""
    out, globals_, missing = [], [], []
    for line in test_src.splitlines():
        m = re.match(r'\s*#include\s+"([^"]+)"', line)
        if m:
            path = find_header(source_root, os.path.basename(m.group(1)))
            if not path:
                missing.append(m.group(1))
                continue
            # Global scope, never inside the namespace: with a unity build and #pragma once, a header first seen
            # inside one test's namespace would be invisible to the next test (found by the unity simulation).
            globals_.append(f'#include "{path}"')
            continue
        elif re.match(r'\s*#include\s+<', line):
            continue  # pre-included outside the namespace
        line = re.sub(r'\bint\s+main\s*\(\s*\)', 'int RunRuleTest()', line)
        out.append(line)
    return '\n'.join(out), globals_, missing


def generate(handoff, source_root, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    made = []
    for system in sorted(os.listdir(handoff)):
        tests = os.path.join(handoff, system, 'Tests')
        if not os.path.isdir(tests):
            continue
        for f in sorted(os.listdir(tests)):
            if not f.endswith('.cpp'):
                continue
            with open(os.path.join(tests, f), encoding='utf-8') as fh:
                body, rule_includes, missing = convert(fh.read(), source_root, system)
            if missing:
                print(f'skip {system}: not integrated ({", ".join(missing)})')
                continue
            ident = re.sub(r'\W', '', system)
            text = '\n'.join([
                f'// Generated by make_ue_rule_tests.py from Handoff/{system}/Tests/{f} - do not edit; regenerate.',
                '#include "Misc/AutomationTest.h"',
                *[f'#include <{h}>' for h in STD],
                *rule_includes,
                '',
                '#if WITH_DEV_AUTOMATION_TESTS',
                f'namespace MurdarRuleTest_{ident}',
                '{',
                body,
                '}',
                '#undef CHECK',
                '#undef NEAR',
                '',
                f'IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMurdarRules_{ident}, "Murdar.Rules.{system}",',
                '\tEAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::EngineFilter)',
                '',
                f'bool FMurdarRules_{ident}::RunTest(const FString&)',
                '{',
                f'\treturn MurdarRuleTest_{ident}::RunRuleTest() == 0; // failures are printed to the log by the test itself',
                '}',
                '#endif',
                '',
            ])
            dst = os.path.join(out_dir, f'RuleTest_{ident}.cpp')
            with open(dst, 'w', encoding='utf-8') as fh:
                fh.write(text)
            made.append(dst)
    print(f'{len(made)} automation test file(s) written to {out_dir}')
    return made


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(2)
    generate(sys.argv[1], sys.argv[2], sys.argv[3])
